apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: services # Match the namespace of LiteLLM deployment for secrets to be accessible

resources:
- litellm-master-key-1password.yaml
- litellm-db-postgres-creds-1password.yaml
- litellm-gemini-1password.yaml