apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: litellm-master-key-1password # This will be the K8s Secret name
spec:
  itemPath: "vaults/HomeLab/items/litellm-master-key-1password" # Adjust path in 1Password