apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: litellm-db-postgres-creds-1password # This will be the K8s Secret name
  namespace: services # Match LiteLLM's namespace
spec:
  itemPath: "vaults/HomeLab/items/litellm-db-postgres-creds-1password" # Adjust if your 1P item is named differently or in another vault