apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: litellm-gemini-1password # This will be the K8s Secret name
spec:
  itemPath: "vaults/HomeLab/litellm-gemini-1password/password" # Adjust path in 1Password