---
- name: "pve_provider"
  node_name: "pve"
  vm_id: 8000
  endpoint: "https://192.168.1.13:8006/"
  username: pulumi@pve
  insecure: True
  hostpcis: ""
- name: "pve2_provider"
  node_name: "pve2"
  vm_id: 8000
  endpoint: "https://192.168.1.14:8006/"
  username: pulumi@pve
  insecure: True
  hostpcis: "gpu"
- name: "pve3_provider"
  node_name: "pve3"
  vm_id: 8000
  endpoint: "https://192.168.1.12:8006/"
  username: pulumi@pve
  insecure: True
  hostpcis: "gpu"
- name: "pve_nas_01_provider"
  node_name: "pve-nas-01"
  vm_id: 8000
  endpoint: "https://192.168.1.15:8006/"
  username: pulumi@pve
  insecure: True
  hostpcis: ""