---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: arr-smb-volume-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
  storageClassName: freenas-nfs-csi
