apiVersion: v1
kind: ConfigMap
metadata:
  name: influxdb-config
  namespace: monitoring
  labels:
    app.kubernetes.io/name: influxdb
    app.kubernetes.io/part-of: monitoring
    app.kubernetes.io/component: database
data:
  influxdb.conf: |
    [meta]
      dir = "/var/lib/influxdb/meta"

    [data]
      dir = "/var/lib/influxdb/data"
      wal-dir = "/var/lib/influxdb/wal"
      cache-max-memory-size = 1073741824
      max-series-per-database = 1000000

    [http]
      auth-enabled = true
      log-enabled = true
      bind-address = ":8086"