apiVersion: v1
kind: Service
metadata:
  name: influxdb-service
  namespace: monitoring
  labels:
    app.kubernetes.io/name: influxdb
    app.kubernetes.io/part-of: monitoring
    app.kubernetes.io/component: database
spec:
  selector:
    app.kubernetes.io/name: influxdb
  ports:
  - port: 8086
    targetPort: influxdb
    name: http
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: influxdb-headless
  namespace: monitoring
  labels:
    app.kubernetes.io/name: influxdb
    app.kubernetes.io/part-of: monitoring
    app.kubernetes.io/component: database
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: influxdb
  ports:
  - port: 8086
    targetPort: influxdb
    name: http