apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: wavy-webhook
  namespace: wavy
  labels:
    app.kubernetes.io/name: wavy
    app.kubernetes.io/component: webhook-server
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: wavy-webhook
subjects:
  - kind: ServiceAccount
    namespace: utilities
    name: wavy-webhook
