apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  log.override: |
    log
  # custom.server: |
  #   example.io:8053 {
  #     forward . 8.8.8.8
  #   } 
  andrewpjackson.db: |
    jellyfin.labs.andrewpjackson.com.    IN    A    192.168.1.40
