apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mcp-servers

resources:
  - gitea-mcp-token-1password.yaml
  - redis-mcp-creds-1password.yaml

commonLabels:
  app.kubernetes.io/part-of: mcp-servers
  app.kubernetes.io/component: secrets