apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jellyseerr
spec:
  project: arr
  source:
    repoURL: 'https://github.com/lordmuffin/homelab.git'
    path: apps/arr/jellyseerr
    targetRevision: main
  destination:
    namespace: jellyseerr
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
    - Validate=false
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=false
    - Prune=false
    retry:
      limit: 10
      backoff:
        duration: 20s
        factor: 2
        maxDuration: 15m
