apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mcp-servers

resources:
  - ./base
  - ./gitea-mcp
  - ./kubernetes-mcp
  - ./postgresql-mcp

commonAnnotations:
  reloader.stakater.com/auto: "true"

commonLabels:
  app.kubernetes.io/part-of: mcp-servers
  app.kubernetes.io/managed-by: kustomize
