apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ha-storage
  namespace: homeassistant
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 40Gi
  storageClassName: freenas-iscsi-csi
