---
kind: Service
apiVersion: v1
metadata:
  name: jellyfin-exporter
  namespace: monitoring
  labels:
    k8s-app: jellyfin-exporter
spec:
  type: ClusterIP
  ports:
  - name: http
    protocol: TCP
    port: 9027
    targetPort: 9027
  selector:
    k8s-app: jellyfin-exporter
