---
kind: Service
apiVersion: v1
metadata:
  name: jellyfin-exporter
  namespace: monitoring
  labels:
    k8s-app: jellyfin-exporter
spec:
  selector:
      app.kubernetes.io/component: exporter
      app.kubernetes.io/name: jellyfin-exporter
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 9027
    targetPort: 9027
  selector:
    k8s-app: jellyfin-exporter
