---
kind: Service
apiVersion: v1
metadata:
  name: jellyfin-exporter
  namespace: monitoring
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port:   '9100'
spec:
  selector:
      app.kubernetes.io/component: exporter
      app.kubernetes.io/name: jellyfin-exporter
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 9027
    targetPort: 9027
