---
kind: Service
apiVersion: v1
metadata:
  name: jellyfin-exporter
  namespace: monitoring
  labels:
    k8s-app: jellyfin-exporter
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 9027
      protocol: TCP
  selector:
    k8s-app: jellyfin-exporter
