apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: db-ganymede
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
spec:
  dockerImage: ghcr.io/zalando/spilo-15:3.0-p1
  teamId: "db"
  numberOfInstances: 1
  users:
    admin:
    - superuser
    - createdb
    twitch: []
  databases:
    vods: twitch
  postgresql:
    version: "15"
  volume:
    size: 1Gi
    storageClass: freenas-iscsi-csi
  additionalVolumes:
  - name: data
    mountPath: /home/postgres/pgdata/partitions
    targetContainers:
    - postgres
    volumeSource:
      PersistentVolumeClaim:
        claimName: ganymede-database
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: postgres-operator
          operator: In
          values:
          - enabled
