apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-technitium-webhook
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: networking
  source:
    repoURL: https://github.com/kittizz/cert-manager-technitium-webhook.git
    path: charts/cert-manager-technitium-webhook
    targetRevision: cert-manager-technitium-webhook-1.0.0
    helm:
      values:
  destination:
    namespace: cert-manager
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - Validate=false
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    - ApplyOutOfSyncOnly=false
    - Prune=true
    - Replace=true
    retry:
      limit: 10
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 60m
