apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: downloads-tls
spec:
  secretName: downloads-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: downloads.gruber.dev.br
  dnsNames:
  - downloads.gruber.dev.br
