apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ./base
namespace: mlops

commonAnnotations:
  reloader.stakater.com/auto: "true"

patches:
- patch: |-
    - op: add
      path: "/spec/template/spec/nodeSelector"
      value:
  target:
    kind: Deployment
    name: turbopilot
