version: '3'
vars:
  CYAN: tput setaf 6
  RED: tput setaf 1
  YELLOW: tput setaf 3
  GREEN: tput setaf 2
  BLUE: tput setaf 1
  PURPLE: tput setaf 5
  BG_B: tput setab 0
  BOLD: tput bold
  RESET: tput sgr0
  CLEAR: tput reset
  PATH_ERROR: is not installed or correctly configured in PATH.
  OP_TOKEN: ""
  ENV: prod-lab

silent: true

tasks:
  clear:
    cmds:
      - sleep 0.1 && {{.CLEAR}}
  reset:
    cmds:
      - |
        sleep 0.1 && \
        {{.RESET}}
  install:
    preconditions:
      - sh: 'which helm'
        msg: 'helm {{.PATH_ERROR}}'
    cmds:
      - kubectl config use-context {{.ENV}} --cluster={{.ENV}}
      - helm repo add 1password https://1password.github.io/connect-helm-charts
      - helm upgrade --install connect 1password/connect --namespace 1password --set-file connect.credentials=/launcher/1password-credentials.json --set operator.create=true --set operator.token.value=${OP_TOKEN}
      - kubectl --context {{.ENV}} delete secret onepassword-token --namespace=1password
      - kubectl --context {{.ENV}} create secret generic onepassword-token --namespace=1password --from-literal=token=${OP_TOKEN} --save-config --dry-run=client -o yaml | kubectl apply -f -
