apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unmanic-data
  namespace: unmanic
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: freenas-iscsi-csi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unmanic-cache
  namespace: unmanic
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: freenas-iscsi-csi
