kind: Deployment
apiVersion: apps/v1
metadata:
  name: handbrake
spec:
  replicas: 1
  selector:
    matchLabels:
      app: handbrake
  template:
    metadata:
      name: handbrake
      labels:
        app: handbrake
    spec:
      # initContainers:
      #   - name: take-data-dir-ownership
      #     image: alpine:3
      #     # Give `grafana` user (id 472) permissions a mounted volume
      #     # https://github.com/grafana/grafana-docker/blob/master/Dockerfile
      #     command:
      #       - chown
      #       - -R
      #       - 1000:1000
      #       - /config/hooks
      #     volumeMounts:
      #       - name: hooks
      #         mountPath: "/config/hooks/pre_conversion.sh"
      #         readOnly: false
      #         subPath: pre_conversion.sh
      #         defaultMode: 0777
      containers:
        - name: handbrake
          image: jlesage/handbrake:v24.03.1
          env:
            - name: USER_ID
              value: "1000"
            - name: GROUP_ID
              value: "1000"
            - name: DARK_MODE
              value: "1"
            - name: SECURE_CONNECTION
              value: "1"
            - name: HANDBRAKE_GUI
              value: "1"
            - name: VNC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: handbrake-vnc-1password
                  key: password
            - name: AUTOMATED_CONVERSION_PRESET
              value: "General/HQ 2160p60 4K HEVC Surround"
          volumeMounts:
            - mountPath: /config
              name: handbrake-config
            - name: hooks
              mountPath: "/config/hooks/pre_conversion.sh"
              readOnly: false
              subPath: pre_conversion.sh
              defaultMode: 0777
            - mountPath: /storage
              name: handbrake-storage
            - mountPath: /watch
              name: arr-smb-volume
              subPath: watch
            - mountPath: /output
              name: arr-smb-volume
              subPath: output
          ports:
            - name: handbrake
              containerPort: 5800
      volumes:
        - name: handbrake-config
          persistentVolumeClaim:
            claimName: handbrake-config-pvc
        - name: handbrake-storage
          persistentVolumeClaim:
            claimName: handbrake-storage-pvc
        - name: arr-smb-volume
          persistentVolumeClaim:
            claimName: arr-smb-volume-pvc
        - name: hooks
          configMap:
            # Provide the name of the ConfigMap you want to mount.
            name: handbrake-hooks
            # An array of keys from the ConfigMap to create as files
            items:
            - key: "pre_conversion.sh"
              path: "pre_conversion.sh"

