---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: handbrake-config-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 25Gi
  storageClassName: freenas-iscsi-csi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: handbrake-storage-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 25Gi
  storageClassName: freenas-iscsi-csi
