apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kasm-app-of-apps
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: apps
  source:
    repoURL: 'https://github.com/lordmuffin/homelab.git'
    path: apps/argocd-cloud/overlays/kasm-apps
    targetRevision: main
  destination:
    namespace: argocd
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 15m