apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kasm
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: apps
  source:
    repoURL: 'https://github.com/kasmtech/kasm-helm.git'
    path: kasm-single-zone
    targetRevision: release/1.17.0
    helm:
      values: |
        global:
          hostname: kasm.lab.apj.dev
          clusterDomain: cluster.local
          image:
            pullPolicy: IfNotPresent
          kasmPasswords:
            adminPassword: "WILL_BE_REPLACED"
            dbPassword: "WILL_BE_REPLACED"
            redisPassword: "WILL_BE_REPLACED"
            encryptionSecret: "WILL_BE_REPLACED"

        kasmApp:
          secrets:
            secretName: kasm-secrets
            existingSecrets:
              adminPassword: "kasm-admin-creds"
              dbPassword: "kasm-db-postgres-creds"
              redisPassword: "kasm-db-postgres-creds"
              encryptionSecret: "kasm-encryption-key"
          ingress:
            enabled: true
            tls:
              enabled: true
              secretName: "lab-apj-dev-tls"
          servicesToDeploy:
            db:
              storageClassName: ""
              resources:
                requests:
                  memory: 1Gi
                  cpu: 500m
                limits:
                  memory: 2Gi
                  cpu: 1000m
            api:
              replicaCount: 1
              resources:
                requests:
                  memory: 1Gi
                  cpu: 500m
                limits:
                  memory: 2Gi
                  cpu: 1000m
            manager:
              replicaCount: 1
              resources:
                requests:
                  memory: 1Gi
                  cpu: 500m
                limits:
                  memory: 2Gi
                  cpu: 1000m
            proxy:
              replicaCount: 1
              resources:
                requests:
                  memory: 1Gi
                  cpu: 500m
                limits:
                  memory: 2Gi
                  cpu: 1000m
            guac:
              replicaCount: 1
              resources:
                requests:
                  memory: 1Gi
                  cpu: 500m
                limits:
                  memory: 2Gi
                  cpu: 1000m
            share:
              replicaCount: 1
              resources:
                requests:
                  memory: 512Mi
                  cpu: 250m
                limits:
                  memory: 1Gi
                  cpu: 500m
            rdpgw:
              replicaCount: 1
              resources:
                requests:
                  memory: 512Mi
                  cpu: 250m
                limits:
                  memory: 1Gi
                  cpu: 500m
  destination:
    namespace: kasm
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
    - Validate=false
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    - ApplyOutOfSyncOnly=false
    - Prune=true
    retry:
      limit: 5
      backoff:
        duration: 20s
        factor: 2
        maxDuration: 15m