apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kasm-utils
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: apps
  source:
    repoURL: 'https://github.com/lordmuffin/homelab.git'
    path: apps/services/kasm
    targetRevision: main
  # Exclude resources that are managed by the kasm Helm chart
  ignoreDifferences:
  - group: ""
    kind: Secret
    name: kasm-secrets
    namespace: kasm
    jsonPointers:
    - /data
  - group: ""
    kind: ConfigMap
    name: kasm-db-configmap
    namespace: kasm
  - group: ""
    kind: ConfigMap
    name: kasm-db-data-sql
    namespace: kasm
  - group: ""
    kind: Secret
    name: kasm-db-cert
    namespace: kasm
  - group: ""
    kind: Namespace
    name: kasm
    jsonPointers:
    - /metadata/finalizers
  - group: ""
    kind: Ingress
    name: kasm-ingress
    namespace: kasm
  destination:
    namespace: kasm
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
    - Validate=false
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    - ApplyOutOfSyncOnly=false
    - Prune=true
    retry:
      limit: 5
      backoff:
        duration: 20s
        factor: 2
        maxDuration: 15m