apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: traefik
  name: traefik-ingress-controller

---
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: traefik
  name: traefik
  labels:
    app: traefik

spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      serviceAccountName: traefik-ingress-controller
      containers:
        - name: traefik
          image: traefik:v2.10
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-dns-home-k3s-lab-1password
                  key: access-key-id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-dns-home-k3s-lab-1password
                  key: secret-access-key
            - name: AWS_REGION
              valueFrom:
                secretKeyRef:
                  name: aws-dns-home-k3s-lab-1password
                  key: aws-region
            - name: AWS_HOSTED_ZONE_ID
              valueFrom:
                secretKeyRef:
                  name: aws-dns-home-k3s-lab-1password
                  key: aws-hosted-zone-id
          args:
            - --api.insecure
            - --accesslog
            - --log.level=DEBUG
            - --entrypoints.web.Address=:8000
            - --entrypoints.websecure.Address=:4443
            - --entrypoints.websecure.http.tls
            - --entrypoints.websecure.http.tls.options=default
            - --providers.kubernetescrd
            - --providers.kubernetescrd.namespaces=traefik
            - --providers.kubernetescrd.ingressclass=traefik
            - --providers.kubernetesingress=true
            - --providers.kubernetesingress.ingressclass=traefik
            - --certificatesresolvers.myresolver.acme.dnschallenge.provider=route53
            - --certificatesresolvers.myresolver.acme.dnschallenge.delaybeforecheck=0
            # - --providers.kubernetesingress.ingressendpoint.publishedservice=default/traefik-in2
            # - --certificatesresolvers.myresolver.acme.tlschallenge
            # - --certificatesresolvers.myresolver.acme.email=dorkmeisterx69@gmail.com
            # - --certificatesresolvers.myresolver.acme.storage=acme.json
            # Please note that this is the staging Let's Encrypt server.
            # Once you get things working, you should remove that whole line altogether.
            # - --certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
          ports:
            - name: web
              containerPort: 8000
            - name: websecure
              containerPort: 4443
            - name: admin
              containerPort: 8080

---
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: traefik
  name: whoami
  labels:
    app: whoami

spec:
  replicas: 2
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      labels:
        app: whoami
    spec:
      containers:
        - name: whoami
          image: traefik/whoami
          ports:
            - name: web
              containerPort: 80
