apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: simpleingressroute
  namespace: traefik
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`whoami.labs.andrewpjackson.com`)
    kind: Rule
    services:
    - name: whoami
      port: 80
      namespace: traefik

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ingressroutetls
  namespace: traefik
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`whoami.labs.andrewpjackson.com`)
    kind: Rule
    services:
    - name: whoami
      port: 80
      namespace: traefik
  tls:
    certResolver: myresolver
