apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
# Traefik CRDs/RBAC
- https://raw.githubusercontent.com/traefik/traefik/v2.10/docs/content/reference/dynamic-configuration/kubernetes-crd-definition-v1.yml
- https://raw.githubusercontent.com/traefik/traefik/v2.10/docs/content/reference/dynamic-configuration/kubernetes-crd-rbac.yml

- services.yaml
- deployment.yaml
- ingressroutes.yaml
- dashboard.yaml
