apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 1password
spec:
  project: core
  source:
    repoURL: https://1password.github.io/connect-helm-charts
    targetRevision: connect-1.14.0
    path: .
    helm:
      releaseName: connect
  destination:
    namespace: 1password
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
      allowEmpty: true
    syncOptions:
    - Validate=false
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    - ApplyOutOfSyncOnly=false
    - Prune=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
