apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kuma-cert
spec:
  secretName: kuma-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: kuma.lab.apj.dev
  dnsNames:
  - kuma.lab.apj.dev
