apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kuma-cloudflare
spec:
  secretName: kuma-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: kuma.labs.andrewpjackson.com
  dnsNames:
  - kuma.labs.andrewpjackson.com
