apiVersion: v1
kind: Service
metadata:
  name: kuma-internal
  labels:
    app: kuma
  annotations:
    kube-vip.io/vipHost: kuma
    kube-vip.io/loadbalancerIPs: 192.168.1.40
spec:
  ports:
    - name: web
      protocol: TCP
      port: 80
      targetPort: 3001
  selector:
    app: kuma
  type: LoadBalancer
  # loadBalancerIP: "192.168.1.22"
  # loadBalancerClass: kube-vip.io/kube-vip-class
