apiVersion: v1
kind: Service
metadata:
  name: kuma-internal
  labels:
    app: kuma
spec:
  ports:
    - name: web
      protocol: TCP
      port: 80
      targetPort: 3001
  selector:
    app: kuma
  type: LoadBalancer
  loadBalancerIP: "0.0.0.0"
  loadBalancerClass: kube-vip.io/kube-vip-class
