apiVersion: v1
kind: Service
metadata:
  name: kuma-internal
  labels:
    app: kuma
spec:
  ports:
    - name: web
      protocol: TCP
      port: 3001
      targetPort: 3001
  selector:
    app.kubernetes.io/name: kuma
  type: LoadBalancer
  loadBalancerIP: "192.168.1.41"
  loadBalancerClass: kube-vip.io/kube-vip-class
