apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: networking
  source:
    repoURL: https://helm.cilium.io/
    chart: cilium
    targetRevision: 1.15.4
    helm:
      releaseName: cilium
      values:
  destination:
    namespace: cilium
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - Validate=false
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    - ApplyOutOfSyncOnly=false
    - Prune=true
    - Replace=true
    retry:
      limit: 10
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 60m
