apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: headscale
spec:
  project: networking
  source:
    repoURL: 'https://github.com/lordmuffin/homelab.git'
    path: apps/networking/headscale
    targetRevision: main
  destination:
    namespace: kube-system
    name: in-cluster
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
      allowEmpty: true
    syncOptions:
    - Validate=false
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=false
    - ApplyOutOfSyncOnly=false
    - Prune=false
    retry:
      limit: 5
      backoff:
        duration: 20s
        factor: 2
        maxDuration: 15m
