apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# - ./external-dns
# - traefik.yaml
- traefik-kustomize.yaml
- cert-manager.yaml
- nginx-ingress.yaml
- tailscale-operator.yaml
- tailscale.yaml
- issuer.yaml
# - kube-vip.yaml
- metallb-service.yaml

namespace: argocd

commonLabels:
  app.kubernetes.io/category: networking
