apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# - ./external-dns
# - cilium.yaml
- metallb-system.yaml
- traefik.yaml
- traefik-kustomize.yaml
- cert-manager.yaml
- keda.yaml
- nginx-ingress.yaml
# - headscale.yaml
- coredns.yaml
# - tailscale-operator.yaml
# - tailscale.yaml
- issuer.yaml
# - kube-vip.yaml


namespace: argocd

commonLabels:
  app.kubernetes.io/category: networking
