apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-patches
spec:
  project: networking
  source:
    repoURL: 'https://github.com/lordmuffin/homelab.git'
    path: apps/networking/traefik
    targetRevision: main
  destination:
    namespace: kube-system
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    managedNamespaceMetadata:
      labels:
        prometheus: enabled
    syncOptions:
    - Validate=false
    - CreateNamespace=false
    - PrunePropagationPolicy=foreground
    retry:
      limit: 5
      backoff:
        duration: 20s
        factor: 2
        maxDuration: 15m
