apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: grill-stats-prod-creds-1password
  namespace: grill-stats
spec:
  itemPath: "vaults/HomeLab/items/grill-stats-prod-creds-1password"