apiVersion: apps/v1
kind: Deployment
metadata:
  name: prowlarr
  namespace: prowlarr
  labels:
    servarr.app: prowlarr
spec:
  replicas: 1
  selector:
    matchLabels:
      servarr.app: prowlarr
  template:
    metadata:
      labels:
        servarr.app: prowlarr
    spec:
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      containers:
        - name: prowlarr
          image: lscr.io/linuxserver/prowlarr:develop
          envFrom:
            - configMapRef:
                name: prowlarr-env
          ports:
            - containerPort: 9696
          volumeMounts:
            - name: data
              mountPath: /config
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: prowlarr-data
