apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "k3s-storage-test.fullname" . }}-data
  labels:
    {{- include "k3s-storage-test.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.storage.accessMode }}
  {{- if .Values.storage.storageClass }}
  storageClassName: {{ .Values.storage.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.storage.size }}

{{- range .Values.storage.classes }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "k3s-storage-test.fullname" $ }}-{{ .name }}
  labels:
    {{- include "k3s-storage-test.labels" $ | nindent 4 }}
    storage-class: {{ .name }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if ne .name "default" }}
  storageClassName: {{ .name }}
  {{- end }}
  resources:
    requests:
      storage: {{ .size }}
{{- end }}