apiVersion: v1
kind: ConfigMap
metadata:
  name: headscale-config
data:
  server_url: "https://hs.labs.andrewpjackson.com:443"
  listen_addr: "0.0.0.0:8080"
  metrics_listen_addr: "127.0.0.1:9090"
  ephemeral_node_inactivity_timeout: "30m"
  derp.server.enabled: "true"
  derp.server.region_id: "999"
  derp.server.region_code: "headscale"
  derp.server.region_name: "Headscale Embedded DERP"
  derp.server.stun_listen_addr: "0.0.0.0:3478"
  derp.server.private_key_path: /var/lib/headscale/derp_server_private.key
  derp.urls: "https://controlplane.tailscale.com/derpmap/default"
  derp.paths: ""
  derp.auto_update_enabled: "true"
  derp.update_frequency: "24h"
  noise.private_key_path: /var/lib/headscale/noise_private.key