namespace: headscale
resources:
  - configmap.yaml
  - ingress.yaml
  - service.yaml
  - statefulset.yaml
  - tailscale-subnet-router.yaml
  - db.yamls
configMapGenerator:
  - name: headscale-site
    files:
      - derp.yaml=site/derp.yaml
    envs:
      - site/public.env
  - name: headscale-etc
    files:
      - config.yaml
# secretGenerator:
#   - name: headscale
#     files:
#       - secrets/private-key
vars:
  - name: PUBLIC_PROTO
    objRef:
      kind: ConfigMap
      name: headscale-site
      apiVersion: v1
    fieldRef:
      fieldPath: data.public-proto
  - name: PUBLIC_HOSTNAME
    objRef:
      kind: ConfigMap
      name: headscale-site
      apiVersion: v1
    fieldRef:
      fieldPath: data.public-hostname
  - name: CONTACT_EMAIL
    objRef:
      kind: ConfigMap
      name: headscale-site
      apiVersion: v1
    fieldRef:
      fieldPath: data.contact-email
