apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
  namespace: jellyfin
  labels:
    app: jellyfin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
    spec:
      securityContext:
        runAsUser: 2775
        fsGroup: 2775
      initContainers:
        - name: example-c
          image: busybox:latest
          command: ["sh", "-c", "mkdir -p /vol-path && chown -R 1000:1000 /vol-path"]
          resources:
            limits:
              cpu: "1"
              memory: 1Gi
          volumeMounts:
            - name: data
              mountPath: /vol-path
      containers:
        - name: jellyfin
          image: lscr.io/linuxserver/jellyfin:latest
          ports:
            - name: web
              containerPort: 8096
            - name: local-discovery
              containerPort: 7359
            - name: dlna
              containerPort: 1900
          volumeMounts:
            - name: data
              mountPath: /config
            - name: movies
              mountPath: /data/movies
            - name: tv
              mountPath: /data/tv
          resources:
            requests:
              cpu: "2"
              # nvidia.com/gpu: 1
            limits:
              cpu: "4"
              # nvidia.com/gpu: 1
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: jellyfin-data-pvc
        - name: movies
          persistentVolumeClaim:
            claimName: jellyfin-movies-pvc
        - name: tv
          persistentVolumeClaim:
            claimName: jellyfin-tv-pvc
