apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: grill-monitoring

resources:
- ../../base
- patches/grill-stats-hpa.yaml

patches:
- path: patches/hpa-patch.yaml
- path: patches/pdb-patch.yaml
- path: patches/resources-patch.yaml
- path: patches/grill-stats-ingress-patch.yaml


patches:
- target:
    kind: ConfigMap
    name: grill-monitoring-config
  patch: |-
    - op: replace
      path: /data/SYNC_INTERVAL
      value: "300"