apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: grill-monitoring

resources:
- ../../base
- ./secrets/grill-stats-prod-creds-1password.yaml
- patches/grill-stats-hpa.yaml
- patches/hpa-patch.yaml
- patches/pdb-patch.yaml

patches:
- path: patches/resources-patch.yaml
- path: patches/grill-stats-ingress-patch.yaml
- path: patches/grill-stats-env-patch.yaml