apiVersion: apps/v1
kind: Deployment
metadata:
  name: ado-agent-deployment
  labels:
    app: ado-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ado-agent
  template:
    metadata:
      labels:
        app: ado-agent
    spec:
      containers:
      - name: ado-agent
        image: git.labs.andrewpjackson.com/healingorganics/azure-pipelines-images/adoagentkeda # replace with your value
        env:
          - name: AZP_URL
            value: https://dev.azure.com/healingorganics # replace with your value
          - name: AZP_POOL
            value: homelab # replace with your value
          - name: AZP_TOKEN
            valueFrom:
              secretKeyRef:
                name: homelab-agent-pool-PAT-1Password
                key: password