apiVersion: v1
kind: ConfigMap
metadata:
  name: glance-cm
data:
  TZ: "America/Chicago"
  PUID: "1000"
  PGID: "1000"
  glance.yml: |
    pages:
      - name: Home
        columns:
          - size: small
            widgets:
              - type: calendar

              - type: rss
                limit: 10
                collapse-after: 3
                cache: 3h
                feeds:
                  - url: https://ciechanow.ski/atom.xml
                  - url: https://www.joshwcomeau.com/rss.xml
                    title: Josh Comeau
                  - url: https://samwho.dev/rss.xml
                  - url: https://awesomekling.github.io/feed.xml
                  - url: https://ishadeed.com/feed.xml
                    title: Ahmad Shadeed

              - type: twitch-channels
                channels:
                  - theprimeagen
                  - cohhcarnage
                  - christitustech
                  - blurbs
                  - asmongold
                  - jembawls

          - size: full
            widgets:
              - type: hacker-news

              - type: videos
                channels:
                  - UCR-DXc1voovS8nhAvccRZhg # Jeff Geerling
                  - UCv6J_jJa8GJqFwQNgNrMuww # ServeTheHome
                  - UCOk-gHyjcWZNj3Br4oxwh0A # Techno Tim

              - type: reddit
                subreddit: selfhosted

          - size: small
            widgets:
              - type: weather
                location: Bloomington, MN

              - type: markets
                markets:
                  - symbol: INSP
                    name: Inspire Sleep
                  - symbol: SPY
                    name: S&P 500
                  - symbol: NVDA
                    name: NVIDIA
                  - symbol: AAPL
                    name: Apple
                  - symbol: MSFT
                    name: Microsoft
                  - symbol: GOOGL
                    name: Google
                  - symbol: AMD
                    name: AMD
      - name: Bookmarks
        columns:
          - size: large
            widgets:
              - type: bookmarks
                groups:
                  - links:
                      - title: Gmail
                        url: https://mail.google.com/mail/u/0/
                      - title: Amazon
                        url: https://www.amazon.com/
                      - title: Github
                        url: https://github.com/
                      - title: Wikipedia
                        url: https://en.wikipedia.org/
                  - title: Entertainment
                    color: 10 70 50
                    links:
                      - title: Netflix
                        url: https://www.netflix.com/
                      - title: Disney+
                        url: https://www.disneyplus.com/
                      - title: YouTube
                        url: https://www.youtube.com/
                      - title: Prime Video
                        url: https://www.primevideo.com/
                  - title: Social
                    color: 200 50 50
                    links:
                      - title: Reddit
                        url: https://www.reddit.com/
                      - title: Twitter
                        url: https://twitter.com/
                      - title: Instagram
                        url: https://www.instagram.com/