apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: glance-storage-pvc
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: sata
