apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secrets-services
spec:
  project: secrets
  source:
    repoURL: https://github.com/lordmuffin/homelab.git
    path: apps/secrets/services
    targetRevision: main
  destination:
    namespace: services
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
      allowEmpty: true
    syncOptions:
    - Validate=false
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    - ApplyOutOfSyncOnly=false
    - Prune=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
