apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: homeassistant

resources:
- ha-db-postgres-creds-1password.yaml
- ha-ssh-key-1password.yaml
- ha-known-hosts-ssh-key-1password.yaml
