apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: grill-stats-dev-creds-1password
  namespace: grill-stats-dev
spec:
  itemPath: "vaults/HomeLab/items/grill-stats-dev-creds-1password"