apiVersion: apps/v1
kind: Deployment
metadata:
  name: vikunja
  labels:
    app: vikunja
  annotations:
    link.argocd.argoproj.io/external-link: https://vikunja.lab.apj.dev
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: vikunja
  template:
    metadata:
      labels:
        app: vikunja
    spec:
      containers:
      - name: vikunja
        image: vikunja/vikunja
        env:
        - name: VIKUNJA_SERVICE_PUBLICURL
          value: "https://vikunja.lab.apj.dev"
        # - name: VIKUNJA_DATABASE_HOST
        #   value: vikunja-database.vikunja.svc.cluster.local
        # - name: VIKUNJA_DATABASE_PASSWORD
        #   valueFrom: {secretKeyRef: {name: vikunja-db-postgres-creds-1password, key: password}}
        # - name: VIKUNJA_DATABASE_USER
        #   valueFrom: {secretKeyRef: {name: vikunja-db-postgres-creds-1password, key: username}}
        - name: VIKUNJA_SERVICE_JWTSECRET
          valueFrom: {secretKeyRef: {name: vikunja-encryption-key-1password, key: password}}
        # envFrom:
        # - configMapRef:
        #     name: vikunja-cm
        ports:
        - name: web
          containerPort: 3456
          protocol: TCP
        resources:
          requests:
            cpu: 150m
            memory: 512Mi
          limits:
            cpu: 550m
            memory: 768Mi
        volumeMounts:
        - name: files
          mountPath: /app/vikunja/files
        - name: db
          mountPath: /db
      initContainers:
        - name: volume-permissions-db
          image: busybox:1.36
          command: ["sh", "-c", "chown 1000:1000 /db"]
          volumeMounts:
            - name: db
              mountPath: /db
      volumes:
      - name: files
        persistentVolumeClaim:
          claimName: vikunja-storage
      - name: db
        persistentVolumeClaim:
          claimName: vikunja-database
      
