vikunja:
  env:
    VIKUNJA_DATABASE_USERNAME:
      valueFrom:
        secretKeyRef:
          name: vikunja-db-postgres-creds-1password
          key: username
    VIKUNJA_DATABASE_PASSWORD:
      valueFrom:
        secretKeyRef:
          name: vikunja-db-postgres-creds-1password
          key: passsword
    VIKUNJA_DATABASE_HOST:
      value: vikunja-database
  persistence:
    data:
      enabled: true
      existingClaim: vikunja-data
  postgresql:
    enabled: false
  redis:
    enabled: true
  typesense:
    enabled: true
    env:
      TYPESENSE_DATA_DIR: /data
      TYPESENSE_API_KEY: typesense
    persistence:
      data:
        # Enabling typesense persistence is recommended to avoid slow reindexing
        enabled: true
        accessMode: ReadWriteOnce
        size: 1Gi
        storageClass: sata