apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ingress.yaml
- db.yaml
- backups.yaml
helmCharts:
- name: vikunja
  repo: oci://ghcr.io/go-vikunja/helm-chart
  version: "1.0.0"
  releaseName: vikunja
  namespace: vikunja
  valuesFile: helm-values.yaml