apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unpackerr-data
  namespace: unpackerr
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: freenas-iscsi-csi
