apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - kasm-app.yaml
  - gitea-app.yaml
  - homepage-app.yaml
  - n8n-app.yaml
  # Add more as needed
  # - media/
  # - mlops/

namespace: flux-system

commonLabels:
  app.kubernetes.io/component: services-application
  category: services