apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wger-cloudflare
spec:
  secretName: wger-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: gym.gruber.dev.br
  dnsNames:
  - gym.gruber.dev.br
