kind: Secret
apiVersion: v1
metadata:
  name: wger-vars
  annotations:
    avp.kubernetes.io/path: "kv/data/wger"
stringData:
  SECRET_KEY: <secret-key>
  SIGNING_KEY: <signing-key>
  EMAIL_HOST_PASSWORD: <path:kv/data/smtp#password>
  EMAIL_HOST_USER: <path:kv/data/smtp#username>
  EMAIL_PORT: <path:kv/data/smtp#port>
  EMAIL_HOST: <path:kv/data/smtp#host>
