apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: grill-monitoring-staging

resources:
- ../../base
- namespace.yaml

patches:
- path: patches/ingress-patch.yaml
- path: patches/grill-stats-ingress-patch.yaml
- target:
    kind: ConfigMap
    name: grill-monitoring-config
  patch: |-
    - op: replace
      path: /data/SYNC_INTERVAL
      value: "180"