apiVersion: v1
kind: Namespace
metadata:
  name: velero
  labels:
    homelab.service: backup
    homelab.component: velero
    name: velero
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged