apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
  labels:
    homelab.service: security
    homelab.component: cert-manager
    name: cert-manager
    cert-manager.io/disable-validation: "true"
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
