apiVersion: v1
kind: Namespace
metadata:
  name: external-dns
  labels:
    homelab.service: networking
    homelab.component: external-dns
    name: external-dns
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
