apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    homelab.service: monitoring
    homelab.component: prometheus
    name: monitoring
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
---
apiVersion: v1
kind: Namespace
metadata:
  name: grafana
  labels:
    homelab.service: monitoring
    homelab.component: grafana
    name: grafana
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted