apiVersion: v1
kind: Namespace
metadata:
  name: security
  labels:
    homelab.service: security
    homelab.component: general
    name: security
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
