apiVersion: v1
kind: Namespace
metadata:
  name: traefik-system
  labels:
    homelab.service: networking
    homelab.component: traefik
    name: traefik-system
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
---
apiVersion: v1
kind: Namespace
metadata:
  name: metallb-system
  labels:
    homelab.service: networking
    homelab.component: metallb
    name: metallb-system
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
