---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyseerr-data-pvc
  namespace: jellyseerr
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
  storageClassName: freenas-iscsi-csi
