apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: secrets
spec:
  description: Secrets Project
  sourceRepos:
  - '*'
  destinations:
  - namespace: kube-system
    server: https://kubernetes.default.svc
  - namespace: 1password
    server: https://kubernetes.default.svc
  - namespace: arr-stack
    server: https://kubernetes.default.svc
  - namespace: argocd
    server: https://kubernetes.default.svc
  - namespace: koordinator-system
    server: https://kubernetes.default.svc
  - namespace: cert-manager
    server: https://kubernetes.default.svc
  - namespace: gitea
    server: https://kubernetes.default.svc
  - namespace: democratic-csi
    server: https://kubernetes.default.svc
  - namespace: 1password
    server: https://kubernetes.default.svc
  - namespace: headscale
    server: https://kubernetes.default.svc
  - namespace: services
    server: https://kubernetes.default.svc
  - namespace: monitoring
    server: https://kubernetes.default.svc
  - namespace: traefik
    server: https://kubernetes.default.svc
  - namespace: tailscale
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  orphanedResources:
    warn: false
