apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - pvc.yaml
  - ingress.yaml
  - backups.yaml

commonLabels:
  app: obsidian
  app.kubernetes.io/name: obsidian
  app.kubernetes.io/component: knowledge-management
