apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: obsidian-pvc
  namespace: services
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ssd
