kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: act-runner-vol
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: freenas-nfs-csi
# ---
# apiVersion: v1
# data:
#   token: << runner registration token goes here >>
# kind: Secret
# metadata:
#   name: runner-secret
# type: Opaque
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: act-runner
  name: act-runner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: act-runner
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: act-runner
    spec:
      restartPolicy: Always
      volumes:
      - name: runner-data
        persistentVolumeClaim:
          claimName: act-runner-vol
      securityContext:
        fsGroup: 1000
      containers:
      - name: runner
        image: gitea/act_runner:act_runner-0.2.10-darwin-amd64
        imagePullPolicy: Always
        command: ["sh", "-c", "(sleep 10 && chmod a+rwx /run/user/1000/docker.sock) & /usr/bin/supervisord -c /etc/supervisord.conf"]
        env:
        - name: DOCKER_HOST
          value: unix:///run/user/1000/docker.sock
        # - name: DOCKER_CERT_PATH
        #   value: /certs/client
        # - name: DOCKER_TLS_VERIFY
        #   value: "1"
        - name: GITEA_INSTANCE_URL
          value: http://gitea-http.gitea.svc.cluster.local:3000
        - name: GITEA_RUNNER_REGISTRATION_TOKEN
          valueFrom:
            secretKeyRef:
              name: gitea-runner-token-1password
              key: password
        securityContext:
          privileged: true
        volumeMounts:
        - name: runner-data
          mountPath: /data

