apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-data
  namespace: sonarr
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: freenas-iscsi-csi
