apiVersion: apps/v1
kind: Deployment
metadata:
  name: qflood
  namespace: unpackerr
  labels:
    servarr.app: qflood
spec:
  replicas: 1
  selector:
    matchLabels:
      servarr.app: qflood
  template:
    metadata:
      labels:
        servarr.app: qflood
    spec:
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      containers:
        - name: qflood
          image: ghcr.io/hotio/qflood:release-42f253d
          envFrom:
            - configMapRef:
                name: qflood-env
          ports:
            - containerPort: 8080
              name: qbittorrent
            - containerPort: 3000
              name: floodui
          volumeMounts:
            - name: data
              mountPath: /config
            - name: downloads
              mountPath: /downloads
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: qflood-data
        - name: downloads
          persistentVolumeClaim:
            claimName: qflood-downloads
