apiVersion: apps/v1
kind: Deployment
metadata:
  name: qflood
  namespace: unpackerr
  labels:
    servarr.app: qflood
spec:
  replicas: 1
  selector:
    matchLabels:
      servarr.app: qflood
  template:
    metadata:
      labels:
        servarr.app: qflood
    spec:
      security_context:
        capabilities:
          - add: ["NET_ADMIN"]
        sysctl:
          - name: "net.ipv4.conf.all.src_valid_mark"
            value: 1
          - name: "net.ipv6.conf.all.disable_ipv6"
            value: 1
      initContainers:
        - image: busybox
          name: copy-wireguard-config
          # command: ["sh", "-c", "mkdir -p /config/wireguard && cp /wireguard/password /config/wireguard/wg0.conf"]
          command: ["sh", "-c", "echo $WIREGUARD"]
          volume_mounts:
            - name: data
              mount_path: "/config"
            - name: wireguard
              mount_path: "/wireguard"
      containers:
        - name: qflood
          image: ghcr.io/hotio/qflood:release-42f253d
          envFrom:
            - configMapRef:
                name: qflood-env
          env:
          - name: WIREGUARD_CONFIG
            valueFrom:
              secretKeyRef:
                name: qflood-wireguard-vpn-1password
                key: password
          ports:
            - containerPort: 8080
              name: qbittorrent
            - containerPort: 3000
              name: floodui
          volumeMounts:
            - name: data
              mountPath: /config
            - name: downloads
              mountPath: /downloads
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: qflood-data
        - name: downloads
          persistentVolumeClaim:
            claimName: qflood-downloads