apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qflood-data
  namespace: qflood
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: freenas-iscsi-csi
