apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: grill-monitoring-db-credentials-1password
  namespace: grill-monitoring
spec:
  itemPath: "vaults/HomeLab/items/grill-monitoring-db-credentials-1password"