apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- resourcequota.yaml
- networkpolicy.yaml
- networkpolicy-api-access.yaml
- configmap.yaml
- secret.yaml
- grill-stats-db-credentials-1password.yaml