apiVersion: v1
kind: ResourceQuota
metadata:
  name: grill-stats-quota
  namespace: grill-stats
spec:
  hard:
    requests.cpu: "6"
    requests.memory: 12Gi
    limits.cpu: "12"
    limits.memory: 20Gi
    persistentvolumeclaims: "15"
    pods: "50"
    services: "20"
    services.loadbalancers: "2"