apiVersion: apps/v1
kind: Deployment
metadata:
  name: kasm-api-deployment
  namespace: kasm
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true,Prune=false
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-hook: Sync
    argocd.argoproj.io/sync-hook-weight: "10"
spec:
  template:
    spec:
      initContainers:
      - name: db-is-ready
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kasm-all-in-one-secrets  # Changed from kasm-secrets
              key: db-password
        command:
        - /bin/bash
        - -c
        args:
        - |
          while [ ! $(PGPASSWORD=$POSTGRES_PASSWORD psql -U kasmapp -d kasm -h db -t -c "select zone_id from zones" 2>/dev/null | wc -l) -ge 2 ]; do 
            echo "Waiting for DB to initialize..."; 
            sleep 5; 
          done
      containers:
      - name: kasm-api-container
        env:
        - name: START_SERVICES
          value: "true"
        - name: KUBERNETES_SERVICE_HOST
          value: "true"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kasm-all-in-one-secrets  # Changed from kasm-secrets
              key: db-password