apiVersion: v1
kind: Secret
metadata:
  name: kasm-db-cert
  namespace: kasm
  annotations:
    argocd.argoproj.io/sync-options: Replace=true
type: Opaque
stringData:
  tls.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDfzCCAmegAwIBAgIUVdpPcaXYXc60Qn/kpDrCPWDbjp0wDQYJKoZIhvcNAQEL
    BQAwTzELMAkGA1UEBhMCVVMxCzAJBgNVBAgMAkNBMRQwEgYDVQQHDAtMb3MgQW5n
    ZWxlczELMAkGA1UECgwCTkExEDAOBgNVBAMMB0thc20gREIwHhcNMjUwNzI5MDQ0
    MTIxWhcNMzUwNzI2MDQ0MTIxWjBPMQswCQYDVQQGEwJVUzELMAkGA1UECAwCQ0Ex
    FDASBgNVBAcMC0xvcyBBbmdlbGVzMQswCQYDVQQKDAJOQTEQMA4GA1UEAwwHS2Fz
    bSBEQjCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBANLy2hSyBH1I5V6b
    7Y2/dz+OkO2sAHEtK7yiDEwLVQeY+7vt5BfCLIUhgLoDezUEne1t3i8SZu0MkOOO
    ZBo/vUXc2ZUUJCplDQTH7DaLK4o2iW0iz2xQlC3/xMeN2Wa0LUhCfwaqqD6sGXIJ
    +vaSJHF4xt/cJcYbDtIZWwPP3X5oHO7BrXwGF5+7DF1SFSAj/jBxWdSLPBlfSRnE
    pFpnhTiOJwrffFIQDZ2DCc1DwcNSj8pu8Zw8JgGF8PbPg6uNgJxKE87D0gHvJTrF
    e5uU2nYeWL1RmSDzxCJn0DzHnykFgAncAxdFu7kRvs1I/+IuZ7HVe1eiucZQFZSB
    Wqo6/T0CAwEAAaNTMFEwHQYDVR0OBBYEFI45t+Yw3cWJFsQqxFV/yHXTQbJ5MB8G
    A1UdIwQYMBaAFI45t+Yw3cWJFsQqxFV/yHXTQbJ5MA8GA1UdEwEB/wQFMAMBAf8w
    DQYJKoZIhvcNAQELBQADggEBAJCtCwKuUwqJ0jfdNrPPmKIY07bHKj/UF/sWUvHC
    8qOhRDnTIUE93aqQsILOIbJ0E3wVL1c7QrYLu3aMmNyLmv3oVnm/Pu2P3maH0gvw
    vkDFyolBpVOFl+hqJQCYUKp9MKJ54u5FTpyWZXLgxvEHS7i+PkdlBHJNifFcpFJ5
    5Xay1AsFWROsI5oLV3jY1lp5XdILRSZqOLCvALK2yNo8Z+Uaxj2t9ykxjkfWXRZQ
    QQF5S5pKn0slZPmGNDWQdXS5KZ0gQUcVqIzxjj2CjQgcGvyzkkVP/7+lO6X1ZPxD
    e9gKqHEf7VhxARPGvoqWhaYiHyW7bUIH0kn5ZaTEY0xfFw0=
    -----END CERTIFICATE-----
  tls.key: |
    -----BEGIN PRIVATE KEY-----
    MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQDS8toUsgR9SOVe
    m+2Nv3c/jpDtrABxLSu8ogxMC1UHmPu77eQXwiyFIYC6A3s1BJ3tbd4vEmbtDJDj
    jmQaP71F3NmVFCQqZQ0Ex+w2iyuKNoltIs9sUJQt/8THjdlmtC1IQn8Gqqg+rBly
    Cfr2kiRxeMbf3CXGG+bSGVsDz91+aBzuwa18Bhefuwxel1Nk3ZQaI/4wcVnUizwZ
    X0kZxKRaZ4U4jicK33xSEA2dgwnNQ8HDUo/KbvGcPCYBhfD2z4OrjYCcShPOw9IB
    7yU6xXublNp2Hli9UZkg88QiZ9A8x58pBYAJ3AMXRbu5Eb7NSP/iLmex1XtXornG
    UBWUgVqqOv09AgMBAAECggEAT3xGC8CYlHr6dHJQQXJ1Y7sd8NoQ8pz6cqTrOuYL
    +KM7sT4CHxfufVxeGO3qiY8/rh1V1I4PGNfuJdtL4jztSuJa5B86B8q4GxD56RYj
    5r8oHKkQmZL9iHAxWkkYz4cZpAhHJbgBmPlaSh2KTdPp4k5hfpz1dhJAQtkxPbIw
    IpvvSrUJN0uyX8xD+m8rYEcRrymsoLZ/RJbO9Ocb5wgXHVUFzFp9gYfDwPXpBjnz
    JfwZbzqTqvF2ZRD4pjqXnAXiEUyv9HwMeRuX3nFkTYx9YbLFzJu5I/H04/JYvpC0
    SoLJO7Ryht96Dy9J7g6Qv3DZ2+2Vk5yGT1hC5/2YXQKBgQD97aBqSV0T5H0IreSk
    HbXKQiJGMnT6m7oYZL4DCvFRXJnT0jF5SLRIQnCpKkSF8p0HpwzCsVkOUVH9SeDj
    1sSN+NmC+S9y2hpLGJ95PjrWHzGLjMPQXRn+4sCkYR3dKrZ2jm2TdpkS7P8sYuHc
    Jtqd2FgxHKu1rQPwCO7mxSzwbwKBgQDUt3/8kpAQz8oXzgmVoqez2+C4pQRxdRvj
    GqDZh5kzZmdqPl11O5bj81yIYbY5cTtJT86GOlc/OX4wOCuqBLI9wTlnqQeOVaHf
    k1L+iyW1iF8GDCBPf9ZZiUYZ6GbI0xRQgRHwJ4jvfP+GWrxFKF3wvNV3C+jGOx+O
    hGwdST51cwKBgQDFqBV6U1IRgPf2oGW1IA6jGMLvL8pxGdGtI6m1SaXn02E1JiWE
    pK2UteuWvL3joKHU+FuH7GIJrSGPemHGUZ/JKk3Qh7eTp2mE9t0XzG4g/9xOYdvN
    aXtVKlH9JG2xYC4yGjzPR5M+6/kPu+U0OO2n9vbdfIzAhB5lVqR9s9zYFQKBgQC6
    dDKtQlzZqQGrgT+3RYNVRBvcVdkJOCJpUlsGi9pKrLW5hCHDW3IRxA3+hqK/jMwm
    OWX9DF2jZjgzw0eNFKpXN1ePJlJVZVx4TGMlqmLGj++v0rzG/dHBp+1hRQdRwjYt
    q1RbBVhwh3vvNX/VFW1lXR/Dox+NSm82TfZn0wAe8wKBgQDMKJpSj6BVvRtA6JCu
    V3NV3lH6a8Nh3r14H6R0vY7TRPyfxBaU3hYPkTzVIWO/j5lbWRWBZlzHuLZfwXtI
    hSw8AQdopwYt6Rb6KjrfTK+e5cKNsrHEsLF/bx8QfIyWpcFcyXX+eYbD81iDbzFm
    1jRyKYXJHvdRP1qNYmM2l+Olow==
    -----END PRIVATE KEY-----