apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kasm-db-statefulset
  namespace: kasm
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/compare-options: IgnoreExtraneous
spec:
  template:
    spec:
      volumes:
      - name: kasm-db-data-sql
        configMap:
          name: kasm-db-data-sql
      containers:
      - name: kasm-db-container
        env:
        # Fix the POSTGRES_PASSWORD secret reference to use kasm-all-in-one-secrets
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kasm-all-in-one-secrets
              key: db-password
        volumeMounts:
        - name: kasm-db-data-sql
          mountPath: /docker-entrypoint-initdb.d/data.sql
          subPath: data.sql