apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kasm-db-statefulset
  namespace: kasm
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/compare-options: IgnoreExtraneous
spec:
  template:
    spec:
      # Updated volumes configuration
      volumes:
      - name: kasm-db-data-sql
        configMap:
          name: kasm-db-data-sql
      # Update the main db-configs volume to use the Helm-created ConfigMap
      - name: kasm-db-configs
        configMap:
          name: kasm-db-init-startup  # Changed from kasm-db-configmap to kasm-db-init-startup
      # Use kasm-db-cert from the kasm application
      - name: kasm-db-cert
        secret:
          secretName: kasm-db-cert
      containers:
      - name: kasm-db-container
        # Replace all environment variables to ensure we override the existing ones
        env:
        - name: POSTGRES_DB
          value: kasm
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kasm-all-in-one-secrets
              key: db-password
        - name: POSTGRES_USER
          value: kasmapp
        volumeMounts:
        - name: kasm-db-data-sql
          mountPath: /docker-entrypoint-initdb.d/data.sql
          subPath: data.sql