apiVersion: v1
kind: ServiceAccount
metadata:
  name: kasm-secret-sync-v2
  namespace: kasm
  labels:
    app: kasm
    component: secret-sync
    version: "v2"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: kasm
  name: kasm-secret-sync-v2
  labels:
    app: kasm
    component: secret-sync
    version: "v2"
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "patch", "update"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kasm-secret-sync-v2
  namespace: kasm
  labels:
    app: kasm
    component: secret-sync
    version: "v2"
subjects:
- kind: ServiceAccount
  name: kasm-secret-sync-v2
  namespace: kasm
roleRef:
  kind: Role
  name: kasm-secret-sync-v2
  apiGroup: rbac.authorization.k8s.io