apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: kasm-all-in-one-secrets
  namespace: kasm
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  itemPath: "vaults/HomeLab/items/KASM All-in-one Secrets"
---
apiVersion: v1
kind: Secret
metadata:
  name: kasm-secrets
  namespace: kasm
  annotations:
    argocd.argoproj.io/sync-options: Replace=true
    argocd.argoproj.io/sync-wave: "1"
type: Opaque
stringData:
  # Keys with kebab-case naming style for the containers
  admin-password: '{{ op://HomeLab/KASM All-in-one Secrets/admin-password }}'
  db-password: '{{ op://HomeLab/KASM All-in-one Secrets/db-password }}'
  redis-password: '{{ op://HomeLab/KASM All-in-one Secrets/redis-password }}'
  encryption-secret: '{{ op://HomeLab/KASM All-in-one Secrets/encryption-secret }}'
  manager-token: '{{ op://HomeLab/KASM All-in-one Secrets/manager-token }}'
  service-token: '{{ op://HomeLab/KASM All-in-one Secrets/service-token }}'
  user-password: '{{ op://HomeLab/KASM All-in-one Secrets/user-password }}'
  
  # Keys with camelCase naming style for the Helm chart
  adminPassword: '{{ op://HomeLab/KASM All-in-one Secrets/admin-password }}'
  dbPassword: '{{ op://HomeLab/KASM All-in-one Secrets/db-password }}'
  redisPassword: '{{ op://HomeLab/KASM All-in-one Secrets/redis-password }}'
  encryptionSecret: '{{ op://HomeLab/KASM All-in-one Secrets/encryption-secret }}'
  managerToken: '{{ op://HomeLab/KASM All-in-one Secrets/manager-token }}'
  serviceToken: '{{ op://HomeLab/KASM All-in-one Secrets/service-token }}'
  userPassword: '{{ op://HomeLab/KASM All-in-one Secrets/user-password }}'