apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - persistent-volume.yaml
  - ingress.yaml
  - ingressroute.yaml
  - rbac.yaml
  - onepassword-items.yaml
  # Comment out the old secrets approach
  # - secrets.yaml
  # Use the new all-in-one secret approach
  - kasm-all-in-one-secret.yaml
  - db-configmap.yaml
  - db-cert.yaml
  - db-data-sql-configmap.yaml
  - db-container-patch.yaml