apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - persistent-volume.yaml
  - ingress.yaml
  - ingressroute.yaml
  - rbac.yaml
  - onepassword-items.yaml
  - secrets.yaml
  - db-configmap.yaml
  - db-cert.yaml
  - db-data-sql-configmap.yaml

patches:
  - path: db-container-patch.yaml
    target:
      group: apps
      version: v1
      kind: StatefulSet
      name: kasm-db-statefulset
      namespace: kasm