apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: kasm-admin-creds
  namespace: kasm
spec:
  itemPath: "vaults/HomeLab/items/kasm-admin-creds-1password"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: kasm-db-postgres-creds
  namespace: kasm
spec:
  itemPath: "vaults/HomeLab/items/KASM All-in-one Secrets"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: kasm-encryption-key
  namespace: kasm
spec:
  itemPath: "vaults/HomeLab/items/kasm-encryption-key-1password"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: kasm-secrets
  namespace: kasm
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  itemPath: "vaults/HomeLab/items/KASM All-in-one Secrets"