apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kasm-profiles
  namespace: kasm
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kasm-uploads
  namespace: kasm
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi