apiVersion: v1
kind: Secret
metadata:
  name: kasm-secrets
  namespace: kasm
type: Opaque
stringData:
  # Keys with kebab-case naming style for the containers
  admin-password: ${kasm-admin-creds}
  db-password: ${kasm-db-postgres-creds}
  redis-password: ${kasm-db-postgres-creds}
  encryption-secret: ${kasm-encryption-key}
  manager-token: ${kasm-db-postgres-creds}
  service-token: ${kasm-db-postgres-creds}
  user-password: ${kasm-db-postgres-creds}
  # Keys with camelCase naming style for the Helm chart
  adminPassword: ${kasm-admin-creds}
  dbPassword: ${kasm-db-postgres-creds}
  redisPassword: ${kasm-db-postgres-creds}
  encryptionSecret: ${kasm-encryption-key}
  managerToken: ${kasm-db-postgres-creds}
  serviceToken: ${kasm-db-postgres-creds}
  userPassword: ${kasm-db-postgres-creds}