apiVersion: v1
kind: Secret
metadata:
  name: kasm-secrets
  namespace: kasm
type: Opaque
stringData:
  adminPassword: ${kasm-admin-creds}
  dbPassword: ${kasm-db-postgres-creds}
  redisPassword: ${kasm-db-postgres-creds}
  encryptionSecret: ${kasm-encryption-key}
  managerToken: ${kasm-db-postgres-creds}
  serviceToken: ${kasm-db-postgres-creds}
  userPassword: ${kasm-db-postgres-creds}