apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: grill-monitoring-dev

resources:
- ../../base

patches:
- target:
    kind: ConfigMap
    name: grill-monitoring-config
  patch: |-
    - op: replace
      path: /data/SYNC_INTERVAL
      value: "60"