apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: grill-monitoring-dev

resources:
- ../../base
- ./secrets/grill-stats-dev-creds-1password.yaml

patches:
- path: ./patches/grill-stats-env-patch.yaml
- path: ./patches/device-service-env-patch.yaml  
- path: ./patches/temperature-service-env-patch.yaml