apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - homelab-main.yaml
  - external-repos.yaml

commonLabels:
  app.kubernetes.io/component: git-source
  source-type: git