apiVersion: apps/v1
kind: Deployment
metadata:
  name: grill-stats
  namespace: grill-stats
spec:
  template:
    spec:
      containers:
      - name: grill-stats
        env:
        - name: THERMOWORKS_API_KEY
          valueFrom:
            secretKeyRef:
              name: grill-stats-prod-creds-1password
              key: THERMOWORKS_API_KEY
        - name: HOMEASSISTANT_URL
          value: "https://home.andrewpjackson.com"
        - name: HOMEASSISTANT_TOKEN
          valueFrom:
            secretKeyRef:
              name: grill-stats-prod-creds-1password
              key: HOMEASSISTANT_TOKEN
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: grill-stats-prod-creds-1password
              key: DB_USERNAME
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: grill-stats-prod-creds-1password
              key: DB_PASSWORD
        - name: POSTGRES_DB
          value: grillstats
        - name: DATABASE_URL
          value: postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@grill-stats-db-rw.grill-stats.svc.cluster.local:5432/$(POSTGRES_DB)
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: grill-stats-prod-creds-1password
              key: REDIS_PASSWORD
        - name: REDIS_URL
          value: redis://:$(REDIS_PASSWORD)@redis.grill-stats.svc.cluster.local:6379/0
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: grill-stats-prod-creds-1password
              key: SECRET_KEY
        - name: FLASK_ENV
          value: production
        - name: SYNC_INTERVAL
          value: "300"
        - name: THERMOWORKS_POLLING_INTERVAL
          value: "300"