node: 192.168.10.50
metadata:
    namespace: config
    type: MachineConfigs.config.talos.dev
    id: v1alpha1
    version: 1
    owner:
    phase: running
    created: 2025-12-07T01:12:04Z
    updated: 2025-12-07T01:12:04Z
spec:
    version: v1alpha1
    debug: false
    persist: true
    machine:
        type: controlplane
        token: ckofdl.fd6uh922qbfnffc2
        ca:
            crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJQekNCOHFBREFnRUNBaEVBb1dFZ2pFMVVJR2NaRjFtZ0FUYkFUVEFGQmdNclpYQXdFREVPTUF3R0ExVUUKQ2hNRmRHRnNiM013SGhjTk1qVXhNakEyTWpNek56VTRXaGNOTXpVeE1qQTBNak16TnpVNFdqQVFNUTR3REFZRApWUVFLRXdWMFlXeHZjekFxTUFVR0F5dGxjQU1oQUpsakY3aFhNNjhtMmltOWY0TWUrSjNDd29wbkdLUmRuOTV5CndaKy9KSVN0bzJFd1h6QU9CZ05WSFE4QkFmOEVCQU1DQW9Rd0hRWURWUjBsQkJZd0ZBWUlLd1lCQlFVSEF3RUcKQ0NzR0FRVUZCd01DTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3SFFZRFZSME9CQllFRktBT3c4eXlHbDlZcGV1MgpOOFVHZGVndTZzUjhNQVVHQXl0bGNBTkJBRlBZZnRLcW5taldlSlVxSlUxVHNGZkd4RVBhR0h2V1NRQ3FyNVRUCnBYemMxNXp5RThyeW9mNmYyNDU4VjlPTnhHYmV5QVdSMmN6dFdzQ0RyUUpSbUE4PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
            key: LS0tLS1CRUdJTiBFRDI1NTE5IFBSSVZBVEUgS0VZLS0tLS0KTUM0Q0FRQXdCUVlESzJWd0JDSUVJQldHTlk0Z0VXa3gwdmNTRVNNYTk2dmFEeTdsRlRvR2swMktVNW44dVNZTwotLS0tLUVORCBFRDI1NTE5IFBSSVZBVEUgS0VZLS0tLS0K
        certSANs: []
        kubelet:
            image: ghcr.io/siderolabs/kubelet:v1.34.0
            defaultRuntimeSeccompProfileEnabled: true
            disableManifestsDirectory: true
        network:
            interfaces:
                - interface: eth0
                  dhcp: true
        install:
            disk: /dev/sda
            image: ghcr.io/siderolabs/installer:v1.11.0
            wipe: false
        features:
            rbac: true
            stableHostname: true
            apidCheckExtKeyUsage: true
            diskQuotaSupport: true
            kubePrism:
                enabled: true
                port: 7445
            hostDNS:
                enabled: true
                forwardKubeDNSToHost: true
        nodeLabels:
            node.kubernetes.io/exclude-from-external-load-balancers: ""
        pods:
            - apiVersion: v1
              kind: Pod
              metadata:
                  name: kube-vip
                  namespace: kube-system
              spec:
                  containers:
                      - name: kube-vip
                        image: ghcr.io/kube-vip/kube-vip:v0.6.4
                        args:
                            - manager
                            - --start-as-leader
                            - --interface=eth0
                            - --vip=192.168.10.20
                            - --controlplane
                            - --services
                            - --arp
                            - --leader-election
                        env:
                            - name: vip_arp
                              value: "true"
                            - name: port
                              value: "6443"
                            - name: vip_interface
                              value: "eth0"
                            - name: vip_cidr
                              value: "32"
                            - name: cp_enable
                              value: "true"
                            - name: cp_namespace
                              value: "kube-system"
                            - name: vip_leaderelection
                              value: "true"
                            - name: vip_leaseduration
                              value: "5"
                            - name: vip_renewdeadline
                              value: "3"
                            - name: vip_retryperiod
                              value: "1"
                            - name: address
                              value: "192.168.10.20"
                            - name: prometheus_server
                              value: ":2112"
                        securityContext:
                            capabilities:
                                add:
                                    - NET_ADMIN
                                    - NET_RAW
                                    - SYS_TIME
                        volumeMounts:
                            - mountPath: /etc/kubernetes/admin.conf
                              name: kubeconfig
                  hostNetwork: true
                  volumes:
                      - hostPath:
                            path: /etc/kubernetes/admin.conf
                        name: kubeconfig
    cluster:
        id: Fx-tXzsjdfL237EaD2LID_5xid1LEfWicvBkzKQGhjU=
        secret: AhBmfFeNSYO+ZDIxdortOfejuIDDwOKmh/9wpxpnawQ=
        controlPlane:
            endpoint: https://192.168.10.20:6443
        clusterName: talos-ha-cluster
        network:
            dnsDomain: cluster.local
            podSubnets:
                - 10.244.0.0/16
            serviceSubnets:
                - 10.96.0.0/12
        token: puy8bl.rzeeaebdhhqrcx07
        secretboxEncryptionSecret: 4iCAAS9y4lLt+2K3+a7eJn7DL80GRqJ10Nz8JS1J/C4=
        ca:
            crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJpekNDQVRDZ0F3SUJBZ0lSQUx2T295TElwOFhHN1Y3QnhDa0l5bll3Q2dZSUtvWkl6ajBFQXdJd0ZURVQKTUJFR0ExVUVDaE1LYTNWaVpYSnVaWFJsY3pBZUZ3MHlOVEV5TURZeU16TTNOVGhhRncwek5URXlNRFF5TXpNMwpOVGhhTUJVeEV6QVJCZ05WQkFvVENtdDFZbVZ5Ym1WMFpYTXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CCkJ3TkNBQVRkdm55cEd6eFFaU2NmenY2YTRNNWRybFk3WjVIUkpPdEJ3T3p4cnkxN0c3MlVzY2ZKUnRSelhBbEUKMEQ5TER4VDNWQ0JNL012Y0xUK29HYXF5cXR2V28yRXdYekFPQmdOVkhROEJBZjhFQkFNQ0FvUXdIUVlEVlIwbApCQll3RkFZSUt3WUJCUVVIQXdFR0NDc0dBUVVGQndNQ01BOEdBMVVkRXdFQi93UUZNQU1CQWY4d0hRWURWUjBPCkJCWUVGQmkzS1RnK3BBSzNoWWpIRXE5NDk5ZUgzT2VrTUFvR0NDcUdTTTQ5QkFNQ0Ewa0FNRVlDSVFEVVRWNGkKSXlpMVE5ay9XZ3JsOHlkMHBjZWlnZ3pnRStJOThvK0NFSUE3ZGdJaEFPTFpxVVQ3QWpueGFiQ2I1S3ZrVEQzbgpNbDRZSzZZSlNGem1XNC9OM0NUOQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
            key: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUpKOHZzWWhiQzBURU5oK3A0NWdqa0Q3UFg3ay9Rd1Nsd3lFeENGS2VWUHdvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFM2I1OHFSczhVR1VuSDg3K211RE9YYTVXTzJlUjBTVHJRY0RzOGE4dGV4dTlsTEhIeVViVQpjMXdKUk5BL1N3OFU5MVFnVFB6TDNDMC9xQm1xc3FyYjFnPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
        aggregatorCA:
            crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJYekNDQVFXZ0F3SUJBZ0lRWEVtcjVaekc5TTFIcnk2QVZIWmV1VEFLQmdncWhrak9QUVFEQWpBQU1CNFgKRFRJMU1USXdOakl6TXpjMU9Gb1hEVE0xTVRJd05ESXpNemMxT0Zvd0FEQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxRwpTTTQ5QXdFSEEwSUFCSWlpdFcvMTFpRm9VS0VoTTFwcStQK1lEZ1Q3dmpQem1GTEE2RTNLdC9xQ3RFUW5QYW10CkxjRlhBSkNTWi9ySTdrTVZCOEo2RW9URk54aWRnOE5mOFRHallUQmZNQTRHQTFVZER3RUIvd1FFQXdJQ2hEQWQKQmdOVkhTVUVGakFVQmdnckJnRUZCUWNEQVFZSUt3WUJCUVVIQXdJd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZApCZ05WSFE0RUZnUVVwdDVKcVhDbkRPbnVpbGxIdVp6a2JUVUhxVDR3Q2dZSUtvWkl6ajBFQXdJRFNBQXdSUUloCkFNV0laNmJVMXpzT1l6UysvY1JwREZ4RTY5WTQ1cFhhdUpMeHlOT0o4eXdJQWlBSTRNZmxzTDFJaXhBNGl0Y0QKdmZKckJJVzNMM01NZ0l2MEo5MFg5L3FXSXc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
            key: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUlCQ2ZpQ3Uyd21oNG1udG9CUUhocXI4bDM2ZEpiNXVFRjFsSUptbVhSRndvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFaUtLMWIvWFdJV2hRb1NFeldtcjQvNWdPQlB1K00vT1lVc0RvVGNxMytvSzBSQ2M5cWEwdAp3VmNBa0pKbitzanVReFVId25vU2hNVTNHSjJEdzEveE1RPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
        serviceAccount:
            key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlKS1FJQkFBS0NBZ0VBbXVzNFphdnIxT1pmTm81cWRQTE1UV1YwVVhvY00rdmg0bEt0WG9WRmZ0NmNFZ3lmCnRnYU9uTFJjOXdYRkFhcGtrZ3NPT3JYRkhDRmxMVEVld3RSMm15c2JGd0ZpeWRySjF4TzkxSGIzM2JBalFaRWoKekJjSWN0Y0FxZ2RwQnhRMEpaVXNwTGdWNkVtU3kxNnBCdllPSjNhVHZJZkZSNW9UdUY4RlRLTWlIUEtIbDloSAp1c2JESGRsYW4vWjg4MmVXd3Jlc0J6VDk0QnlCUWF6R1ZkVFlqZnFmQXQ0b0hJWWhpc2JMSllmUkhjR3NsQml6CnBxZ0M0bE4ycFVaNEcvcjZVdEE3SmpucXowc2VVMkx4TnFyV0VXY3g3VWhJMjAydWp4TENxWG1vNGhrRkR2UEwKdzA1V3hOOTh5dVhjT0xlNTZZbG1GcUdFVDJBWFQyS0YxenU3WFpVWVR1dWxBYVh0SDBQOUl2VXJxb29JRW9Dbwpvd29UR3BzU0JXOVZBWXlNdGFFdktKQVNwNGFGTTdMZ25sZzc2bllOYUx6WkluSitlc0YxaXBkY1BFcGdrMmxsCjlWbGJRRGsvblM3YU5pOVdiM0srNTNtRzVBKzYxR3pXSHBqeE5KVit6a0RMMTdGcGFqOEZPcnlybVJPWU0vVFMKbkhhTEc5QjJOMExiOW5keDU0QmlvTmR1M3FiUll1M2dsd3ZlaWdmM2t5VWRZSlFMY1NaNWFnRmJxTWZ6eHJlVgp6NVl2dzNmbkhJa0JRN1AxWU54YWRCQzJ5bVBDMGNZakRrZWkwN1pVRzdpZ1FaMXloZ0tIakEvalB2dElLVGhaCnJYVnhwT3NyUFg5bzhaVmdLcUZpcmljWkdhM21aaTdXaDZIcjlvTHhsWjcveVBndk92a0gxVDlyTTk4Q0F3RUEKQVFLQ0FnQXhLY0NtRTE4dUcwWFFESFlnVXdVZThybHRPZkZGVVBCSVlMQ0FOSThQYWhuaGFId3V5Zm5zSlJqegprN01uaWltTVoxSEdzL1N2cnJGckhCR0ZCdVAwN2tNVWsrNEQzUmo4MWxrQjJoZGpGUWk3UUJJNkxIMFQ1TU5qCk1pTFVpa2JhUG5NQ2V5RUlySUNYWlowQ2hvZUxZb2dUNW9wbTVMQ3BiQTVFZWVqVGd1d2c5aFFkWkFKN3NJU2cKQ3hzd0s0bWVsYWRVU2k3Zk5teVdxUHZ3TlRIY0xOTFZtQ2JtbG5LQ2xmL1dFem43MVlDdEp3R3NPOWxlZGRwTApMUWZrNlVzVGlOMmNqZmpFZkRSTmhqTENoSWlXMFViNDVGMnFxd1pnaFRXZGp1eFhoRlVrbjUza2h6SG1ISDUvCjdWNXI2WEpvZUtBYlFucTRyZWYzMjI1YUZheXAwY0ltdkpmcFVsSlNJeW04bkp5c1N1aStpell5RXh4V0xTOEsKeWJuR0M1RkdkUlFLUXRnQUY0SG1peWp5OEJXbzVEMnAvSkI4Qm1VNW9obmdhbUhzemdoY1ZGWlBEbnd2S2RBVApOcE15eHZYcHhVbG9ObGVpUHQrUDh0cUV3OTVJV2RYSEt4eXBsNGErNUxIRndWaGUwall5bUwrY0xuWXJET3ZuCkZJNFF1czZaZWF0cThhUWZBcHBQRW5jSEVhWUNCQlYrRjRRd3hwOS9GQk9lR3lYVDRrc01CMFVtVUYwN1ZQTkQKT2lWK29ZSGFNVDZyTjBoMWRXbmszVSs1OWhRVGZwdmhBU0lpdUJJVXloSG1XTlFoNytIakFkTTUzNnhmdFRlUQp4c2NwaGZjVmtSQWk4SkpDWGx4bXYvVDJQd0FKTjNXWEVIcmNnRkRmd1UxQ24yVEI0UUtDQVFFQXlvL1VxZ1FxCmd1MnVxNi9BVlBYVEhpa0NzNklFMjJsS1h5UHoyNGNJcFovdEkydXhOY1NpQU1DUmVTRTlQZnZyMjdLVGFCUXMKT1lFOGJaMVg2dExwNFhnRm9TcFRPQzNrdXV1b1RPdHNvZ1FTcHozd1Y1S3hBQlRJeFVPd2RQbG5CeGZKcEU1cApvNUU1OFNuKzJBUFRMeHRabmdmcGNQZ1FBWW1aTnFNT1NMcHZ3ZCt2VHdPZUZ4VDNjcWQ0N2s3UnRpMGg3U0FOClQ3Rmkzcml3UFNtZHZuQkZ1eUNqR0N2bjJ6MDVTcFBCMzFITDc1Qk5DTFo4Rm8zK3cxWjJ2MDJLRjExcTM5eWwKK09qczMraTFHNDF6a1l5ZVhwRGpCYldWL21PYllZa3dJcHZSYzEyNWNGVDJIalBFbkFuTW5sVXp5blFVelF6SgpSQlhmaklkVEpUek90d0tDQVFFQXc4bklTUlJaRVB0bG1ONjdNam9kSk54bzVLQUxaU2wzR1dCUjZ6RFF1K2JHCnNKZlR1M2ZEQXV6Q2oyeHczcXJzQ3RuaCsxb1d3YWJQYUlFOTN6SVAzbGhwbGVHOG04aHR6eUgrbVR0Q0RkRmgKamxhNk96ejhway9HV2JtVHdHenVkLytwREFLdFdCQVhKdFE4cXMxV2NOaDRYNVBwMGV3TG1STFMrR1FTR0lVTQpFQlZ2cVVWQ1RPZytVcWJlaTB0SmFsYzZvUFRIZ0lPaml2LzlzN1BRc1F6M0pjQjF3cnFURmZqN2VabVdoWlhmCms3eVZHUXBxSlZWajN4N3NNZ1haOGtjZks4a21GeVhjY0RVSEJpQzc0UWhLSWxySEdoeHJkOVJ2UUkrcm40TzcKaHA5UEpwMU9IaWEyL0lsWlo3U3hjZm1lbFFWczZ3RWJsbnpFYWhrY0dRS0NBUUFvblBYeXNLc2xYU3BzV2V5aQpIRGVjRUhUdU4wbnFCQTVaVFFnVHQ5dFArZVM5K1ZXcWhpWkZLRmNDaGx1VkZmR1FOeG0vQUd4dGl5L21lbW1xCk4yZVZRVTgvcFJEU2JzRXhpUlpSZGRKdUdZcno1VU5QQzZaWmNkRmZXOWNCWFEvL0tCSFIwN2J5aUtlcFp0WWwKMFg2Q0wyV2tmY21jVU9CRXJxWDlnbXZXd1NxdklINHh4WFBwQk5jb01kUFpWQXhRRG5TQzZxNUFrRHhXazRraQplam1hZVVCQjZLVktyMkxwWGpraWJzV3NWT1lpdmpmenkwTE44dUpsbit4bkp0RE5Kbm5MTUo1R2JjMHdoNlBvClJsQXBtcHdXTWM2UzBubWthNnczdmgzY2tvbElMRDZGKzBMdGcwdWtUWUt0TEVBYUUzUW9PS3dSN3FESHVFby8KYVJXNUFvSUJBUUNkMlAvdDAwYmZoeDlvK1NHSkpBczlIYW8vc0x5ZkthZ0l3SHdyRnVjaXByTkh5cEI4MHRoWgpjbEtGMlZMQ1lxRDlPcDZUekJVT3VaTDhXVDV0eE9uQVJCMlVKak91a1EvZThEUllpOHI4WXZPNUV6ai82M0p5CkQxMEdGN1VFYlk1eEZxRE91eFhRS3VEUGdFc05GWkY4VnpudExNNVZYVzRZVW5IZXFxZGdOMXY3VjV6M3Bvd0cKZnpOSDVac0VTSVYvQTZhVC8rVWNPb1ZPMm9aTExFeXpnWlY4VFVkajRKSVhJKzV6SWgyVnc3aEdYc01DTmtCUApxeUZpMElaeTZmN0Y4d3N4ZlBHRnRoT2NMMVJqWDE2NTFib1hLb0xkRFU2amhKVFJRME9Gem1vUTVqMmxEeXZjCjZTK2NPSXZwTFdmbVVPN0dqR0k4c1Y3eG05T3JDbVY1QW9JQkFRQ3lsZDYzUjZIU1lXa21vNEFSbDZJQUZaL20KYTZVWXRuVWgwOElmQXpsaVgvZ2JXVnEvQitlMlZjTTRnQ2dPRjJWbWtuSEpSMC8zQS95ODZ6bUNLU3laSG1pNApvY2lwdjA1bm4yV1NsWWx6QlNMNjlaZlhGWHQwczdab1ZpREhQSzEyZ1J4eDZlR2h6TTJ1OUlWMmdPYVpPQXJiCmN3NmhzNmc1YjR6UmRoSDlyNmg4a2ZIL2ZlOUI4TTNSQVZzZ0Z6dXhsbUxGbHIvcHNyUFh0VnRCRHJFS2Q4SVgKRzlzS3hpeWdBRk9ETTZNRVJqcGlha1Z6TmlZbXd3N1c3MlBMNWFXaWtJZElndHNCWnNxc1RkTVk0MytLZFV5dgpabnFoYjdXSXd4SlFyakZIMDNIL1BVOUxtMEhjb1c0WEFMQ3NoV0N3VWhzLzZQdHhYUzBES01sc2VmNUUKLS0tLS1FTkQgUlNBIFBSSVZBVEUgS0VZLS0tLS0K
        apiServer:
            image: registry.k8s.io/kube-apiserver:v1.34.0
            certSANs:
                - 192.168.10.20
            disablePodSecurityPolicy: true
            admissionControl:
                - name: PodSecurity
                  configuration:
                    apiVersion: pod-security.admission.config.k8s.io/v1alpha1
                    defaults:
                        audit: restricted
                        audit-version: latest
                        enforce: baseline
                        enforce-version: latest
                        warn: restricted
                        warn-version: latest
                    exemptions:
                        namespaces:
                            - kube-system
                        runtimeClasses: []
                        usernames: []
                    kind: PodSecurityConfiguration
            auditPolicy:
                apiVersion: audit.k8s.io/v1
                kind: Policy
                rules:
                    - level: Metadata
        controllerManager:
            image: registry.k8s.io/kube-controller-manager:v1.34.0
        proxy:
            image: registry.k8s.io/kube-proxy:v1.34.0
        scheduler:
            image: registry.k8s.io/kube-scheduler:v1.34.0
        discovery:
            enabled: true
            registries:
                kubernetes:
                    disabled: true
                service: {}
        etcd:
            ca:
                crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJmakNDQVNPZ0F3SUJBZ0lRVmxScUtaU3RBMmJJd0lkQjljTVNtVEFLQmdncWhrak9QUVFEQWpBUE1RMHcKQ3dZRFZRUUtFd1JsZEdOa01CNFhEVEkxTVRJd05qSXpNemMxT0ZvWERUTTFNVEl3TkRJek16YzFPRm93RHpFTgpNQXNHQTFVRUNoTUVaWFJqWkRCWk1CTUdCeXFHU000OUFnRUdDQ3FHU000OUF3RUhBMElBQklNV1VNeVFVVUZOCkFFY3Vld0ZUcUxtY3pIYnJxejVrNGhYVVEyL2hpM2xvVTR0ZkdCb3BPSUdweUEzS3lxMHJjSDV4UnpvMGdIdUwKWm5kSG1scWdvbWlqWVRCZk1BNEdBMVVkRHdFQi93UUVBd0lDaERBZEJnTlZIU1VFRmpBVUJnZ3JCZ0VGQlFjRApBUVlJS3dZQkJRVUhBd0l3RHdZRFZSMFRBUUgvQkFVd0F3RUIvekFkQmdOVkhRNEVGZ1FVYlV4S0ZMdXZWTkM5CmpzOTRwTCtDT1Flb2h1MHdDZ1lJS29aSXpqMEVBd0lEU1FBd1JnSWhBT25NeC9KdDFoU21FK3IzaGFiYUloaWwKNlprR2tUYThGRlNJTCt6MmNpM2VBaUVBcHJGQzZHRE5GanN1cGRXVDI0bWpHSjZYSlFUQnFUWFdLand2VzFBTgpBZnM9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
                key: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUpreE4rTWszemQxTFZPUG9RU1hPYWxLNVQ2NTQ5aEMrc05FMDc5d0tPd2lvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFZ3haUXpKQlJRVTBBUnk1N0FWT291WnpNZHV1clBtVGlGZFJEYitHTGVXaFRpMThZR2lrNApnYW5JRGNyS3JTdHdmbkZIT2pTQWU0dG1kMGVhV3FDaWFBPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
