apiVersion: v1
kind: Service
metadata:
  name: homepage-internal
  labels:
    app: homepage
  annotations:
    kube-vip.io/vipHost: homepage
spec:
  ports:
    - name: dashboard-server
      port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    app: homepage
  type: ClusterIP