apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- blinko-db-postgres-creds-1password.yaml
- blinko-nextauth-secret-1password.yaml
- backblaze-cloud-homelab-creds-1password.yaml