apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tandoor

resources:
- tandoor-db-postgres-creds-1password.yaml
- tandoor-secret-creds-1password.yaml
- backblaze-cloud-homelab-creds-1password.yaml