---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: grafana-internal
  annotations:
    external-dns.alpha.kubernetes.io/hostname: grafana.labs.andrewpjackson.com
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
    external-dns.alpha.kubernetes.io/ttl: "120"
    cert-manager.io/cluster-issuer: letsencrypt-production
    acme.cert-manager.io/http01-edit-in-place: "true"
    kubernetes.io/ingress.class: traefik-external
  labels:
    app: grafana
spec:
  entryPoints:
    - web-int-tls
  routes:
    - match: Host(`grafana.labs.andrewpjackson.com`)
      kind: Rule
      services:
        - name: grafana-internal
          port: 8081
  tls:
    secretName: labs-andrewpjackson-com-tls
