apiVersion: v1
kind: Endpoints
metadata:
  name: k3s-metrics-service
  namespace: monitoring
subsets:
- addresses:
  - ip: 10.1.0.1
  - ip: 10.1.0.2
  - ip: 10.1.0.3
  - ip: 10.1.0.4
  - ip: 10.1.0.5
  ports:
  - name: https-metrics
    port: 10250
    protocol: TCP
