---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: paperless
  namespace: paperless
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: paperless
  template:
    metadata:
      labels:
        app: paperless
    spec:
      initContainers:
      - name: wait-for-db
        image: busybox:1.37
        command: ['sh', '-c', 'until nc -z db 5432; do echo "Waiting for Postgres..."; sleep 5; done']
        imagePullPolicy: IfNotPresent
      containers:
      - name: paperless
        image: ghcr.io/paperless/paperless:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: PAPERLESS_OCR_LANGUAGES
          value: jpn
        - name: PAPERLESS_OCR_LANGUAGE
          value: eng+jpn
        - name: PAPERLESS_REDIS
          value: redis://redis:6379
        - name: PAPERLESS_DBHOST
          value: paperless-database.paperless.svc.cluster.local
        - name: PAPERLESS_DBNAME
          value: paperless
        - name: PAPERLESS_DBUSER
          value: paperless
        - name: PAPERLESS_URL
          value: https://paperless.lab.apj.dev
        - name: PAPERLESS_CSRF_TRUSTED_ORIGINS
          value: https://paperless.lab.apj.dev
        - name: PAPERLESS_DBPASS
          valueFrom: {secretKeyRef: {name: paperless-db-postgres-creds-1password, key: password}}
        - name: PAPERLESS_ADMIN_USER
          valueFrom: {secretKeyRef: {name: paperless-admin-creds-1password, key: username}}
        - name: PAPERLESS_ADMIN_PASSWORD
          valueFrom: {secretKeyRef: {name: paperless-admin-creds-1password, key: password}}
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: media
          mountPath: /usr/src/paperless/media
        - name: consume
          mountPath: /usr/src/paperless/consume
        startupProbe:
          tcpSocket:
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 6
        livenessProbe:
          tcpSocket:
            port: 8000
        readinessProbe:
          tcpSocket:
            port: 8000
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "4Gi"
            cpu: "2"
      volumes:
      - name: media
        persistentVolumeClaim:
          claimName: paperless-media
      - name: consume
        persistentVolumeClaim:
          claimName: paperless-consume