apiVersion: v1
kind: Service
metadata:
  name: paperless
  labels:
    app: paperless
spec:
  selector:
    app: paperless
  ports:
    - name: web
      port: 8000
      targetPort: 8000
      protocol: TCP
  type: ClusterIP
