apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kasm

resources:
  - kasm-admin-creds-1password.yaml
  - kasm-db-postgres-creds-1password.yaml
  - kasm-encryption-key-1password.yaml

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: kasm-admin-creds
    behavior: replace
    options:
      annotations:
        argocd.argoproj.io/sync-options: Replace=true
    envs:
      - .kasm-admin-creds.env
  - name: kasm-db-postgres-creds
    behavior: replace
    options:
      annotations:
        argocd.argoproj.io/sync-options: Replace=true
    envs:
      - .kasm-db-postgres-creds.env
  - name: kasm-encryption-key
    behavior: replace
    options:
      annotations:
        argocd.argoproj.io/sync-options: Replace=true
    envs:
      - .kasm-encryption-key.env