apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kasm

resources:
  - kasm-admin-creds-1password.yaml
  - kasm-db-postgres-creds-1password.yaml
  - kasm-encryption-key-1password.yaml

generatorOptions:
  disableNameSuffixHash: true
