apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: whisparr-data
  namespace: whisparr
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: freenas-iscsi-csi
