apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: technitium-letsencrypt
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: dorkmeisterx69@gmail.com
    privateKeySecretRef:
      name: acme-letsencrypt-key-prod
    solvers:
    - selector:
        dnsNames:
        - '*.lab.apj.dev'
        - lab.apj.dev
        - '*.apj.dev'
        - apj.dev
        - dashboard.lab.apj.dev
      dns01:
        webhook:
          groupName: acme.xver.cloud
          solverName: technitium
          config:
            serverUrl: https://172.234.198.221:53443
            authTokenSecretRef:
              key: password
              name: technitium-api-key-homelab-cloud-1password    
