apiVersion: v1
kind: Secret
metadata:
  name: headscale-certificate
  namespace: headscale
  labels:
    cnpg.io/reload: ""
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: headscale-certificate
  namespace: headscale
spec:
  secretName: headscale-certificate-tls
  usages:
    - server auth
    - client auth
  commonName: hs.labs.andrewpjackson.com
  dnsNames:
    - hs.labs.andrewpjackson.com
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
    group: cert-manager.io
