apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- clusterIssuer.yaml
# - postgres.yaml
- labs-andrewpjackson-com.yaml
- svc-cluster-local.yaml

patches:
 - target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: redis.redis.redis.opstreelabs.in
   path: redis-patch.yaml
 - target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: redisclusters.redis.redis.opstreelabs.in
   path: redis-patch.yaml
 - target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: redisreplications.redis.redis.opstreelabs.in
   path: redis-patch.yaml
 - target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: redissentinels.redis.redis.opstreelabs.in
   path: redis-patch.yaml
