---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: svc-cluster-local
  namespace: cert-manager
spec:
  secretName: svc-cluster-local-tls
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: argocd, redis-operator"
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
  commonName: "*.svc.cluster.local"
  dnsNames:
  - "*.svc.cluster.local"
  - "webhook-service.redis-operator.svc"
  - "*.svc"
