---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tandoor
  name: tandoor
spec:
  replicas: 1
  strategy: {}
  selector:
    matchLabels:
      app: tandoor
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: tandoor
    spec:
      restartPolicy: Always
      securityContext:
        fsGroup: 1000
      containers:
      - name: recipes
        image: vabene1111/recipes
        imagePullPolicy: Always
        # command: ["sh", "-c", "(sleep 10 && chmod a+rwx /run/user/1000/docker.sock) & /usr/bin/supervisord -c /etc/supervisord.conf"]
        env:
        - name: UID
          value: "1000"
        - name: GID
          value: "1000"
        - name: TZ
          value: "America/Chicago"
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: tandoor-secret-creds-1password
              key: password
        - name: DB_ENGINE
          value: django.db.backends.postgresql
        - name: POSTGRES_HOST
          value: tandoor-database-rw.tandoor.svc.cluster.local
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_DB
          value: tandoor
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: tandoor-db-postgres-creds-1password
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: tandoor-db-postgres-creds-1password
              key: password
        # - name: SOCIALACCOUNT_PROVIDERS
        #   value: |
        #     {
        #       "microsoft": {
        #           "APPS": [
        #               {
        #                   "client_id": "<insert-id>",
        #                   "secret": "<insert-secret>",
        #                   "settings": {
        #                       "tenant": "organizations",
        #                       # Optional: override URLs (use base URLs without path)
        #                       "login_url": "https://login.microsoftonline.com",
        #                       "graph_url": "https://graph.microsoft.com",
        #                   }
        #               }
        #           ]
        #       }
        #     }
        ports:
          - name: web
            containerPort: 8080
            protocol: TCP
        volumeMounts:
        - name: recipes-static
          mountPath: /opt/recipes/staticfiles
        - name: recipes-media
          mountPath: opt/recipes/mediafiles
      volumes:
        - name: recipes-static
          persistentVolumeClaim:
            claimName: recipes-static
        - name: recipes-media
          persistentVolumeClaim:
            claimName: recipes-media