apiVersion: apps/v1
kind: Deployment
metadata:
  name: unpackerr
  namespace: unpackerr
  labels:
    servarr.app: unpackerr
spec:
  replicas: 1
  selector:
    matchLabels:
      servarr.app: unpackerr
  template:
    metadata:
      labels:
        servarr.app: unpackerr
      annotations:
        ravianand.me/config-hash: <computed-sha1-hash>
    spec:
      securityContext:
        runAsUser: 2775
        fsGroup: 2775
      initContainers:
        - name: copy-config
          image: busybox
          command: ["sh", "-c", "cp /tmp/unpackerr.conf /config/unpackerr.conf"]
          volumeMounts:
            - name: config
              mountPath: /tmp
            - name: data
              mountPath: /config
      containers:
        - name: unpackerr
          image: golift/unpackerr
          volumeMounts:
            - name: data
              mountPath: /config
            - name: downloads
              mountPath: /downloads
          resources:
            limits:
              cpu: "2"
          env:
          - name: UN_SONARR_0_API_KEY
            valueFrom:
              configMapKeyRef:
                name: sonarr-api-key-1password
                key: password
          - name: UN_RADARR_0_API_KEY
            valueFrom:
              secretKeyRef:
                name: radarr-api-key-1password
                key: password
      volumes:
        - name: downloads
          persistentVolumeClaim:
            claimName: qflood-downloads
        - name: data
          persistentVolumeClaim:
            claimName: unpackerr-data
        - name: config
          configMap:
            name: unpackerr-conf
            items:
              - key: unpackerr.conf
                path: unpackerr.conf
