apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lidarr-data
  namespace: lidarr
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: freenas-iscsi-csi
