apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: auth
spec:
  forwardAuth:
    address: https://auth.labs.andrewpjackson.com/_oauth
    trustForwardHeader: true
    authResponseHeaders:
      - X-Forwarded-User