---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: actual-db-postgres-creds-1password
  namespace: services
spec:
  itemPath: "vaults/homelab/items/actual-db-postgres-creds"