apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: paperless

resources:
- paperless-admin-creds-1password.yaml
- paperless-db-postgres-creds-1password
- backblaze-cloud-homelab-creds-1password.yaml