apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: git-cloudflare
spec:
  secretName: git-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: git.labs.andrewpjackson.com
  dnsNames:
  - git.labs.andrewpjackson.com
