apiVersion: redis.redis.opstreelabs.in/v1beta1
kind: Redis
metadata:
  name: gitea-redis
  namespace: gitea
spec:
  kubernetesConfig:
    image: redis:7.2.3
    imagePullPolicy: IfNotPresent
    updateStrategy:
      type: OnDelete
    resources:
      requests:
        cpu: 150m
        memory: 128Mi
      limits:
        cpu: 250m
        memory: 256Mi
  storage:
    volumeClaimTemplate:
      spec:
        storageClassName: freenas-iscsi-csi
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 2Gi
  nodeSelector:
    kubernetes.io/arch: amd64
