apiVersion: v1
kind: Service
metadata:
  name: gitea-internal
  labels:
    app: gitea
  annotations:
    kube-vip.io/vipHost: gitea
spec:
  ports:
    - name: http
      port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    app: gitea
  type: ClusterIP