apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - core-namespaces.yaml
  - app-namespaces.yaml
  - monitoring-namespaces.yaml
  - networking-namespaces.yaml

commonLabels:
  app.kubernetes.io/component: namespace
  managed-by: fluxcd